site:
  name:
    class: text
    custom: Ever Fu
  # ç½‘é¡µicon
  # Web icon
  siteIcon: https://s3.qjqq.cn/47/66399928e7379.webp!color
  icon: https://s3.qjqq.cn/47/66399928e7379.webp!color

nav:
  group:
    é¡¹ç›®: # åˆ†ç±»åç§°
      Solitude: https://github.com/everfu/hexo-theme-solitude || https://s3.qjqq.cn/47/66399928e7379.webp!color # å­èœå•åç§°(submenu name): é“¾æ¥åœ°å€(address) || å›¾æ ‡(icon)

  menu:
    æ–‡åº“: # æ˜¾ç¤ºåç§° / Display name
      å…¨éƒ¨æ–‡ç« : /archives/ || st-folder-fill # å­èœå•åç§°ï¼šè·¯å¾„ || å›¾æ ‡ / Submenu name: path || icon
      åˆ†ç±»åˆ—è¡¨: /categories/ || st-checkbox-multiple-blank-fill
      æ ‡ç­¾åˆ—è¡¨: /tags/ || st-price-tag-fill
    å‹é“¾:
      å‹æƒ…é“¾æ¥: /links/ || st-group-fill
      å®è—åšä¸»: javascript:travelling() || st-gift-fill
    å…³äº:
      éŸ³ä¹: /music/ || st-disc-fill
      å…³äºæœ¬ç«™: /about/ || st-contacts-fill
    ç•™è¨€æ¿: /message/

  right:
    random: true # éšæœºæ–‡ç« è·³è½¬ / random post button
    custom:
      - name: travelling - å‹é“¾æ¥åŠ› # æ˜¾ç¤ºæ–‡å­— / Displayed text
        url: https://www.travellings.cn/go.html # è·³è½¬é“¾æ¥ / Jump link
        icon: st-train-line # å›¾æ ‡ / Icon
        onclick: # ç‚¹å‡»äº‹ä»¶ / Click event
        id: travellings_button # id
      - name: Post Chat
        onclick: javascript:togglePostChatContainer(); return false;
        icon: st-robot-fill
        id: post_chat_button

hometop:
  enable: true # æ˜¯å¦æ‰“å¼€ / if enable
  # banner display
  banner:
    # å·¦ä¸Šè§’æ˜¾ç¤ºå¤§æ–‡å­—
    # Large text displayed in the upper left corner
    # tipï¼šå¯ä½¿ç”¨htmlæ ‡ç­¾
    # tip: html tags be used
    title: å®é™è‡´è¿œ<br>çƒ­çˆ±ç”Ÿæ´»
    # å·¦ä¸Šè§’æ˜¾ç¤ºå°æ–‡å­—
    # Small text displayed in the upper left corner
    url: Hexo Theme Solitude
    # è½®æ’­icon
    # Carousel icon
    # tip: 76x76 size
    icon:
#      HTML: # åå­— / Name
#        img: https://7.isyangs.cn/34/65f2e42921677-34.png # å›¾ç‰‡ / Image
#        color: "#e9572b" # èƒŒæ™¯è‰² / Background color
#      JS:
#        img: https://7.isyangs.cn/34/65f2e43ceddda-34.png
#        color: "#f7cb4f"
#      Docker:
#        img: https://7.isyangs.cn/34/65f2e45462045-34.png
#        color: "#57b6e6"
#      Flutter:
#        img: https://7.isyangs.cn/34/65f2e47acbe98-34.png
#        color: "#ffffff"
#      WebPack:
#        img: https://7.isyangs.cn/34/65f2e488bf8ed-34.png
#        color: "#2e3a41"
#      Git:
#        img: https://7.isyangs.cn/34/65f2e499066fa-34.png
#        color: "#df5b40"

  # å·¦ä¸‹è·³è½¬æŒ‰é’®
  # Banner lower left jump button
  group:
     çƒ­é—¨: /tags/çƒ­é—¨/ || st-fire-fill || linear-gradient(to right,#f65,#ffbf37)
     æ•™ç¨‹: /tags/æ•™ç¨‹/ || st-book-mark-fill || linear-gradient(to right,#358bff,#15c6ff)
     ç²¾é€‰: /tags/ç²¾é€‰/ || st-star-smile-fill || linear-gradient(to right,#18e7ae,#1eebeb)

  # å³ä¾§ç½®é¡¶åˆ—è¡¨ï¼ˆåœ¨æ–‡ç« çš„front matterä¸­æ·»åŠ â€œrecommend: trueâ€ï¼‰
  # Right top list (add "recommend: true" in the front matter of the article)
  recommendList:
    # å·¦ä¸Šè§’æ˜¾ç¤ºæ–‡å­—
    # Large text displayed in the upper left corner
    sup: ç½®é¡¶
    # å·¦ä¸‹è§’å¤§å­—
    # Large text in the lower left corner
    title: Solitude ä¸»é¢˜æ–‡æ¡£
    # ç‚¹å‡»è·³è½¬é“¾æ¥
    # Click the jump link
    url: https://solitude.js.org/
    # æ˜¾ç¤ºèƒŒæ™¯å›¾ç‰‡
    # Display background image
    img: https://s3.qjqq.cn/47/668da89f2b920.png!color
    # é˜´å½±é¢œè‰²
    # Shadow color
    color: "none"

aside:
  home:
    noSticky: "about"
    Sticky: "allInfo"
  post:
    noSticky: "about"
    Sticky: "newestPost"
  page:
    noSticky: "about"
    Sticky: "newestPost,allInfo"
  position: 1
  card:
    style: 1
    author:
      img: https://s3.qjqq.cn/47/6625c1a86d7fd.webp!color
      sticker:
    url: /about/
    content: åˆ†äº«æ–°çŸ¥è¯†ï¼Œè®°å½•ç”Ÿæ´»ç‚¹æ»´ã€‚
    content2: æœ¬ç«™ç”± Hexo å¼ºåŠ›é©±åŠ¨ï¼Œä¸»é¢˜ä¸º Solitudeã€‚
    sayhello: # æ ·å¼ä¸º2æ—¶æ— æ•ˆ
      morning: âœ¨ æ—©ä¸Šå¥½å•Šï¼Œæ–°çš„ä¸€å¤©å¼€å§‹äº†
      noon: ä¸­åˆåº”è¯¥ä¼‘æ¯ä¸€ä¸‹å’¯
      afternoon: ä¸‹åˆèŒ¶æ—¶é—´åˆ°äº† ğŸµ
      night: æ—©ç¡æ—©èµ·èº«ä½“å¥½
      goodnight: æ™šå®‰ï¼Œå¥½æ¢¦ ğŸ˜´
    sayhello2: # æ ·å¼ä¸º2æ—¶æ— æ•ˆ
      - ä½ ä¼šæˆåŠŸçš„
      - ä½ ä¸€å®šä¼šæˆåŠŸçš„
      - ç¥ä½ å¥½è¿ï¼Œé™Œç”Ÿäºº
    information: # æ ·å¼ä¸º1æ—¶è¯·ä¸è¦è¶…è¿‡4ä¸ª
      Github: https://github.com/everfu || st-github-line
      Bilibili: https://space.bilibili.com/1329819902 || st-bilibili-line

  toc:
    post: true
    page: false
    vague: true

  tags:
    enable: true
    limit: 20
    highlight_list:
    #  - Hexo

  archive:
    enable: false
    # æ˜¾ç¤ºç±»å‹
    type: "month" # month: æŒ‰æœˆ / year: æŒ‰å¹´ : month: by month / year: by year

  # å»ºç«™ä¿¡æ¯
  # Website information
  siteinfo:
    # æ–‡ç« æ•°
    # Number of articles
    postcount: true
    # æ€»å­—æ•°
    # The number of words on the web site
    wordcount: true
    # è®¿é—®é‡
    # PV
    pv: true
    # è®¿å®¢æ•°
    # UV
    uv: true
    # æœ€åæ›´æ–°æ—¥æœŸ
    # Last update date
    updatetime: false
    # å»ºç«™æ—¶é—´
    # Website creation time
    runtimeenable: true
    # æ ¼å¼ï¼šyyyy-MM-dd hh-mm-ss
    # Format: yyyy-MM-dd hh-mm-ss
    runtime: "2023-04-20 00:00:00"

# é¦–é¡µæ–‡ç« é…ç½®ä¿¡æ¯
# Configure information on the home page
index_post_list:
  direction: column # row / column
  column: 2 #2:2åˆ— 3:3åˆ—
  content: 2 # 1: post.description / 2: è‡ªåŠ¨è·å–descriptionæˆ–æˆªå–å†…å®¹(Automatically get descriptions or screenshots) / 3: åªä½¿ç”¨æˆªå–å†…å®¹(Use only screenshots) / false: ä¸æ˜¾ç¤ºå†…å®¹(No content is displayed)
  length: 200 # æˆªå–å†…å®¹çš„é•¿åº¦ : The length of the screenshot content
  cover: both # left: åœ¨å·¦ä¾§ : left / right: åœ¨å³ä¾§ : right / both: ä¸¤ä¾§ : both

# é¡µé¢é»˜è®¤è®¾ç½®
# page default settings
page:
  error: true # 404é¡µé¢ / 404 page
  tags: true # æ ‡ç­¾é¡µ /  Tags page
  categories: true # åˆ†ç±»é¡µ /  Categories page
  default: # é»˜è®¤å€¼ /  Default value
    # é»˜è®¤å›¾ç‰‡
    # default cover
    cover:
    # - /img/default.avif # é»˜è®¤å›¾ç‰‡ / default cover

# æ–‡ç« é¡µé»˜è®¤è®¾ç½®
# post default settings
post:
  default:
    # æ–‡ç« é»˜è®¤å›¾ç‰‡
    # default cover
    cover:
    # -  # é»˜è®¤å›¾ç‰‡ / default cover
    # æ–‡ç« å‘å¸ƒé»˜è®¤åœ°å€
    # default post locate
    locate: è¡¡é˜³
    # æ–‡ç« é»˜è®¤ç‰ˆæƒ
    # default post copyright
    copyright:
      enable: true
      author:
        url: /about/ # ç‚¹å‡»å¤´åƒè·³è½¬åœ°å€
        img: # æ˜¾ç¤ºå¤´åƒï¼Œä¸å¡«å†™é»˜è®¤æ˜¾ç¤ºsite_icon
      license: CC BY-NC-SA 4.0
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
  # é¡¶éƒ¨æ–‡ç« ç®€ä»‹
  # Top article introduction
  meta:
    date: true # å‘å¸ƒæ—¥æœŸ / Release date
    updated: true # æ›´æ–°æ—¥æœŸ / Update date
    locate: false # ä½ç½® / Location
    wordcount: true # å­—æ•° / Number of words
    readtime: true # è®¿é—® / uv
    pv: true # æµè§ˆé‡ / pv
    comment: false # è¯„è®ºæ•° / Comment count
  # æ‰“èµ
  # reward
  award:
    enable: true
    appreciators: /about # èµèµè®°å½• / Appreciative records
    title: æ„Ÿè°¢æ‚¨çš„èµèµã€‚
    desc: å› ä¸ºæœ‰ä½ ä»¬çš„æ”¯æŒï¼Œæˆ‘æ‰ä½“ä¼šåˆ°å†™æ–‡ç« çš„ä»·å€¼ã€‚
    list:
      - name: çˆ±å‘ç”µ
        qcode: https://s3.qjqq.cn/47/661ba8e695f17.webp!color
        url: https://afdian.net/a/everfu/
        color: var(--efu-purple)
      - name: æ”¯ä»˜å®
        qcode: https://s3.qjqq.cn/47/66374315ebd08.webp!color
        url: https://s3.qjqq.cn/47/66374315ebd08.webp!color
        color: var(--efu-blue)
      - name: å¾®ä¿¡
        qcode: https://s3.qjqq.cn/47/663742bac8e52.webp!color
        url: https://s3.qjqq.cn/47/663742bac8e52.webp!color
        color: var(--efu-green)
  # åˆ†äº«æŒ‰é’®ï¼Œéœ€è¦æ˜¯ä»€ä¹ˆå“ªäº›æŒ‰é’®ï¼Œå¡«å†™åå¼€å¯
  share:
    enable: true
    list:
      - qq
      - weibo
      - twitter
      - facebook
      - telegram
      - whatsapp
      - linkedin
      - link
      - qrcode
  # ç‰ˆæƒä¸­è®¢é˜…æŒ‰é’®è·³è½¬é“¾æ¥ï¼Œå¡«å†™åœ°å€åå¼€å¯
  # Subscription button jump link in copyright
  rss: /atom.xml
  covercolor:
    enable: true
    mode: api # localï¼šæœ¬åœ°å–è‰² / apiï¼šimg2colorå–è‰² : local: local color / api: img2color color
    api: https://api.qjqq.cn/api/Imgcolor?img= # apiåœ°å€ / api address
    time: 43200000 # apiå–è‰²é—´éš”ï¼ˆæ¯«ç§’ï¼‰ï¼Œé»˜è®¤ä¸º12å°æ—¶ / api color interval (milliseconds), default is 12 hours
  footer:
    enable: true
    desc: æ¥è‡ª Ever Fu çš„æ–‡ç« ã€‚
    button: # è·³è½¬æŒ‰é’®
      enable: false
      name: More
      url: /about/

theme_color:
  dark: "#ffc848"
  dark_op: "#f2b94b23"
  dark_op_deep: "#f2b94bdd"
  dark_none: "#f2b94b00"
  light: "#425AEF"
  light_op: "#4259ef23"
  light_op_deep: "#4259efdd"
  light_none: "#4259ef01"

display_mode:
  type: auto
  universe: false

related_post:
  enable: true
  limit: 2
  date_type: created

footer:
  information:
    author: false
    left:
      Github: https://github.com/everfu || st-github-line
      é‚®ç®±: mailto:o@efu.me || st-mail-line
    right:
      Bç«™: https://space.bilibili.com/1329819902 || st-bilibili-line
      æŠ–éŸ³: https://v.douyin.com/iJsLc8jt/ || st-douyin-fill

  group:
    é¡¹ç›®:
      æ–‡æ¡£: https://solitude.js.org
      åœ°å€: https://github.com/everfu/hexo-theme-solitude
    èµåŠ©:
      çˆ±å‘ç”µ: https://afdian.net/a/everfu/
      æ”¯ä»˜å®: https://s3.qjqq.cn/47/66374315ebd08.webp!color
      å¾®ä¿¡: https://s3.qjqq.cn/47/663742bac8e52.webp!color
  randomlink: true
  privacy: /privacy/
  license: /license/
  links:
    - name: ä¸»é¢˜
      url: https://github.com/everfu/hexo-theme-solitude
    - name: è®¢é˜…
      url: /atom.xml

errorpage:
  img: /img/404.avif
  text: è¯·å°è¯•ç«™å†…æœç´¢å¯»æ‰¾æ–‡ç« 
  recommendList: true

says:
  enable: false
  home_mini: false
  style: 1
  strip: 30

recent_comments:
  enable: true
  limit: 50
  cache: 0.2
  console: true
  page: /recentcomments/

envelope:
  enable: true
  line: 10 # æ˜¾ç¤ºè¡Œæ•°
  speed: 20 # æ’­æ”¾é€Ÿåº¦
  hover: true # é¼ æ ‡æ‚¬åœæš‚åœ
  loop: true # å¾ªç¯æ’­æ”¾
  page: /message/ # ç•™è¨€æ¿é¡µé¢ / message board page

meting_api: "https://meting.qjqq.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r"

music:
  enable: true
  id: 8407304077
  server: netease
  type: playlist
  volume: 0.8
  mutex: true

capsule:
  enable: true
  id: 8407304077
  server: netease
  type: playlist

copy:
  enable: true
  copyright:
    enable: false
    limit: 50 # word count. ï¼ˆå­—æ•°ï¼‰

# æ‡’åŠ è½½
# lazyload
lazyload:
  enable: true
  field: site # post, site
  placeholder: /img/loading.avif
  errorimg: /img/error_load.avif

loading:
  fullpage: true
  pace: true

highlight:
  enable: true
  limit: 200 # ä»£ç è¡Œé«˜é™åˆ¶ / Code line limit
  copy: true # æ˜¯å¦å¼€å¯å¤åˆ¶æŒ‰é’® / Whether to enable the copy button
  expand: true # æ˜¯å¦é»˜è®¤å±•å¼€ / Whether to expand by default
  theme: mac # default: é»˜è®¤ / mac : apple terminal
  color: default # default: é»˜è®¤  / solidity: solidity / dracula: dracula

lightbox: true
fancybox: true
mediumZoom: false

mermaid: true

OpenGraph:
  enable: true
  options:
  #  twitter_card:
  #  twitter_image:
  #  twitter_id:
  #  twitter_site:
  #  google_plus:
  #  fb_admins:
  #  fb_app_id:

wordcount: true

busuanzi: true
busuanzi_use: 0 # 0: åŸç‰ˆ / 1: é’ç§¸(other: å…¶å®ƒè‡ªå®šç¾©çš„busuanziå¹³å°)

search:
  enable: true
  type: local
  tags:
    - Solitude
  algolia:
  # hits:
  #   per_page: 6
  local:
    preload: false
    CDN:

tianli_talk:
  enable: true
  title: æ–‡ç«  AI
  key: efd0a84058a25af978278dd67927c53195ba # https://ai.tianli0.top/?InviteID=OZ3Z0V2R
  option: #https://ai.tianli0.top/codeMaker.html
    defaultInput: true
    upLoadWeb: true
    userTitle: Efu Chat
    userDesc: æˆ‘æ˜¯ Efu Chatï¼Œä¸€ä¸ªç”± Ever Fu å¼€å‘çš„èŠå¤©åŠ©æ‰‹ã€‚
    showInviteLink: 'https://ai.tianli0.top/?InviteID=OZ3Z0V2R'
    blackDom:
      - .aplayer
post_ai:
  enable: true
  modelName: Efu Chat
  key: efd0a84058a25af978278dd67927c53195ba
  talk: æˆ‘æ˜¯ Efu Chatï¼Œä¸€ä¸ªç”± Ever Fu å¼€å‘çš„èŠå¤©åŠ©æ‰‹ã€‚æˆ‘è´Ÿè´£æ–‡ç« çš„èŠå¤©å±•ç¤ºã€‚ä½ ä¸èƒ½ç›´æ¥ä¸æˆ‘äº¤æµï¼Œä½†æˆ‘å¯ä»¥å›ç­”ä¸€äº›é¢„è®¾é—®é¢˜ã€‚
  randomPost: true
  report:
  tips:

katex:
  enable: true
  per_page: true # æ˜¯å¦åœ¨æ¯é¡µéƒ½åŠ è½½ / Whether to load on each page
  copytex: true # æ˜¯å¦å¼€å¯å¤åˆ¶å…¬å¼ / Whether to enable copy formula

comment:
  use: twikoo # waline, twikoo, valine, artalk
  commentBarrage: false # çƒ­è¯„å¼€å…³ / Hot comment switch
  lazyload: false # æ‡’åŠ è½½
  count: true # è¯„è®ºæ•°å±•ç¤º
  pv: false # æ˜¯å¦ä½¿ç”¨è©•è«–çµ±è¨ˆé é¢è¨ªå•
  avatar: https://cravatar.cn # Gravatar link
  newest_comment:
    enable: true
    storage: .5
  hot_tip: # å¤šäººäº’åŠ¨
    enable: true # å¼€å¯åå°†åœ¨æ–‡ç« åˆ—è¡¨æ˜¾ç¤ºå¤šäººäº’åŠ¨
    count: 3 # è®¾ç½®å¤§äºå¤šå°‘è¯„è®ºæ—¶æ˜¾ç¤º

twikoo: # https://twikoo.js.org/
  envId: https://everfu-twikoo.netlify.app/.netlify/functions/twikoo # ä½ éƒ¨ç½²twikooçš„åœ°å€
  lang: "zh-CN" # è¯­è¨€
  accessToken: # accessTokenï¼ˆåœ¨æµè§ˆå™¨æ§åˆ¶å°cookiesè·å–ï¼‰

console:
  enable: true
  recentComment:
    enable: true
    storage: .2
  card:
    tags: true
    archive: true

extends:
  head: # åœ¨headä¸­æ’å…¥ / Insert in head
  # - <script src="https://cdn.bootcdn.net/ajax/libs/pace/1.2.4/pace.min.js"></script>
  body: # åœ¨bodyä¸­æ’å…¥ / Insert in body

pwa:
  enable: false
  manifest: /manifest.json # manifest.json æ–‡ä»¶è·¯å¾„
  theme_color: "#006a73" # ä¸»é¢˜é¢œè‰²
  mask_icon: /img/pwa/favicon.ico # é®ç½©å›¾æ ‡
  apple_touch_icon: /img/pwa/favicon.ico # è‹¹æœè§¦æ‘¸å›¾æ ‡
  bookmark_icon: /img/pwa/favicon.ico # ä¹¦ç­¾å›¾æ ‡
  favicon_32_32: /img/pwa/favicon_32.ico # 32x32å›¾æ ‡
  favicon_16_16: /img/pwa/favicon_16.ico # 16x16å›¾æ ‡

google_adsense:
  enable: false
  auto_ads: false # è‡ªåŠ¨å¹¿å‘Šå…³é—­ååˆ™ä¸ºæ‰‹åŠ¨å¹¿å‘Š / After auto ads are turned off, it is manual ads
  enable_page_level_ads: true # é¡µé¢çº§å¹¿å‘Š / Page-level ads
  aside_card: true # ä¾§è¾¹æ å¡ç‰‡å¹¿å‘Š / Sidebar card adsï¼ˆå¼€å¯åè‡ªè¡Œåˆ°éœ€è¦æ·»åŠ çš„é¡µé¢ä½¿ç”¨ï¼šadsï¼‰
  post_card: true # æ–‡ç« å¡ç‰‡å¹¿å‘Š / Post card adsï¼ˆé¦–é¡µæ–‡ç« åˆ—è¡¨ï¼‰
  post_content: true # æ–‡ç« å†…å®¹å¹¿å‘Š / Post content adsï¼ˆæ–‡ç« å†…å®¹åº•éƒ¨å¹¿å‘Šï¼‰
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js # è°·æ­Œå¹¿å‘Šjs / Google Adsense js
  # client id
  # æ— è®ºæ˜¯å¦å¼€å¯è‡ªåŠ¨å¹¿å‘Šï¼Œéƒ½éœ€è¦å¡«å†™ client id
  # Whether to enable auto ads or not, you need to fill in the client id
  client: ca-pub-6338523842252061 # ca-pub-XXXXXXXXXXXXXX
  # slot id
  # åªæœ‰å…³é—­è‡ªåŠ¨å¹¿å‘Šæ—¶æ‰éœ€è¦å¡«å†™ slot idï¼Œå¯ä»¥åœ¨è°·æ­Œå¹¿å‘Šåå° æŒ‰å¹¿å‘Šå•å…ƒä¸­åˆ›å»ºå¹¿å‘Šä½åè·å–
  # Only when auto ads are turned off, you need to fill in the slot id, which can be obtained after creating an ad space in the Google Adsense background according to the ad unit
  slot: # 4236388782

right_menu:
  enable: true
  custom_list:
    - name: éšå³æ–‡ç« 
      click: toRandomPost()
      id: menu-randomPost
      class:
      icon: st-signal-tower-fill
    - name: å…¨éƒ¨åˆ†ç±»
      click: pjax.loadUrl('/categories/') # å¤–é“¾ç”¨ window.openï¼Œpjax æ— æ³•è¯·æ±‚è·¨åŸŸå†…å®¹
      id:
      class:
      icon: st-checkbox-multiple-blank-fill
    - name: å…¨éƒ¨æ ‡ç­¾
      click: pjax.loadUrl('/tags/')
      id:
      class:
      icon: st-price-tag-fill
    - name: èµåŠ©ä¸»é¢˜
      click: window.open('https://afdian.net/a/everfu/', '_blank')
      id:
      class:
      icon: st-afdian-line

memorial:
  enable: true
  # æ—¥æœŸ, (M-D)
  # Date, (M-D)
  # eg: 7-8, 9-18, 12-13 ...
  date:
    - "7-7" # ä¸ƒä¸ƒäº‹å˜
    - "9-18" # ä¹ä¸€å…«äº‹å˜/å»ºå†›èŠ‚
    - "12-13" # å—äº¬å›½å®¶å…¬ç¥­æ—¥

lure:
  enable: true
  # è·³å‡º
  # Jump out
  jump: "404 Not Found"
  # åˆ‡å›
  # Switch back
  back: "ãƒ¾(â‰§âˆ‡â‰¦*)ã‚å˜¿å˜¿ï¼Œä¸Šå½“äº†å§"

# æ–‡ç« è¿‡æœŸæé†’
# Article expiration reminder
expire:
  enable: true
  # è¿‡æœŸæ—¶é—´
  # Expiration time
  time: 60 # 30å¤© / 30 days
  position: top # top / bottom
  # è¿‡æœŸæç¤º
  # Expiration prompt
  text_prev: "æœ¬æ–‡å·²äº"
  text_next: "å¤©å‰è¿‡æœŸï¼Œå¦‚æœå†…å®¹ä¸ç¬¦ï¼Œè¯·è”ç³»ç«™é•¿æ›´æ–°ã€‚"

# èƒŒæ™¯å›¾ç‰‡
# Background image
background:
  enable: true
  img: https://img.truimo.com/2022/807b270630a51.jpg
  opacity: 0.2

CDN:
  internal: local
  third_party: cdnjs
  version: true
  custom_format: //open.lightxi.com/cdnjs/ajax/libs/${cdnjs_name}/${version}/${min_cdnjs_file}

  option:
    solitude_css: https://cdn2.codesign.qq.com/icons/7pOrz0WXB5ZWJPX/latest/iconfont.css
    busuanzi_qj_js: https://pv.lemonso.com/js
    # algolia_search:
    # instantsearch:
    # pjax:
    # twikoo:
    # waline_js:
    # waline_css:
    # katex:
    # katex_copytex:
    # lazyload:
    # aplayer_css:
    # aplayer_js:
    # meting_js:
    # pace_js:
    # swiper_css:
    # swiper_js:
    # busuanzi_js:
    # snackbar_js: